import { nbk7Ior } from "../transport/spectrum";

const range = (
  id: string,
  label: string,
  min: number,
  max: number,
  step: number,
  value: number,
): string =>
  `<label class="range"><span class="field"><span>${label}</span><input id="${id}-value" type="number" min="${min}" max="${max}" step="${step}" value="${value}" disabled></span><input id="${id}" type="range" aria-label="${label}" min="${min}" max="${max}" step="${step}" value="${value}" disabled></label>`;
const select = (id: string, label: string, options: string): string =>
  `<label class="field"><span>${label}</span><select id="${id}" disabled>${options}</select></label>`;
const group = (label: string, body: string, open = false): string =>
  `<details ${open ? "open" : ""}><summary>${label}</summary><div class="group">${body}</div></details>`;
export function renderEditor(controlScene: boolean): string {
  return `
<main class="editor">
  <header class="topbar"><div class="brand"><h1>WebGPU Path Tracer</h1><span>WebGPU · Cornell / Suzanne</span></div><div class="top-actions"><button id="reset" disabled>Сброс камеры</button><button id="pause" disabled>Пауза</button></div></header>
  <div class="workspace">
    <section class="viewport-area"><div class="viewport-toolbar"><div class="profile-buttons"><button data-profile="preview" disabled>Preview</button><button data-profile="reference" disabled>Reference</button><button data-profile="quality" disabled>Quality</button></div></div>
      <div class="viewport"><canvas aria-label="Progressive path traced image"></canvas><div class="viewport-overlay"><strong id="scene-name">Suzanne / N-BK7</strong><span id="activity">Подготовка сцены…</span><span id="progress">0 samples</span></div><div id="error" role="alert" hidden></div></div>
      <div class="viewport-help">ЛКМ — вращение · Колесо — приближение · Настройки применяются автоматически</div>
    </section>
    <aside class="inspector" aria-label="Настройки сцены"><div class="inspector-title">Настройки</div><div class="view-setting"><label class="field"><span>Вид</span><select id="view" aria-label="Вид" disabled><option value="beauty">Изображение</option><option value="normal">Нормали</option><option value="depth">Глубина</option><option value="bvh">Обход BVH</option><option value="wavelength">Длина волны</option><option value="path-length">Длина PT-пути</option><option value="photon-density">Плотность фотонов</option><option value="material">Материалы</option></select></label><p class="hint">BVH: посещённые узлы на видимом участке луча до первой поверхности.</p></div>
      ${group("Рендер", select("profile", "Режим", '<option value="preview">Preview</option><option value="reference">Reference</option><option value="quality">Quality</option><option value="custom">Вручную</option>') + select("mode", "Перенос", '<option value="rgb">RGB</option><option value="spectral">Спектральный</option>') + select("integrator", "Интегратор", '<option value="pt">Path tracing</option><option value="sppm">SPPM</option>') + select("resolution", "Пиксельный бюджет", '<option value="19200">160 × 120</option><option value="76800">320 × 240</option><option value="307200">640 × 480</option><option value="691200">960 × 720</option><option value="2073600">1920 × 1080</option>') + range("max-depth", "Глубина пути", 1, 64, 1, 32) + select("strategy", "Семплирование", '<option value="mis">MIS</option><option value="light">Light only</option><option value="bsdf">BSDF only</option>') + '<label class="field"><span>Seed</span><input id="seed" type="number" min="0" max="4294967295" step="1" value="1" disabled></label><label class="field"><span>Цель samples / iter.</span><input id="sample-limit" type="number" min="0" max="1048576" step="1" value="0" disabled></label><p class="hint">Цель 0 — накопление без ограничения.</p><label class="check"><input id="auto-preview" type="checkbox" checked disabled>Preview при движении камеры</label><p class="hint">Reference: спектральный PT. Quality: спектральный SPPM с каустиками. Возврат после 250 мс покоя.</p>', true)}
      ${group("Камера", range("fov", "Вертикальный FOV, °", 15, 90, 1, 40) + range("camera-distance", "Дистанция, м", 0.25, 12, 0.05, 3.7) + '<p class="hint">Вращение и zoom сохраняют цель камеры. Сброс возвращает исходный ракурс.</p>')}
      ${group("Сцена и свет", select("scene", "Объект", '<option value="suzanne">Suzanne</option><option value="control">Контрольная сфера</option>') + range("object-scale", "Масштаб объекта", 0.25, 1.4, 0.01, 1) + range("object-x", "Позиция X, м", -0.35, 0.35, 0.01, 0) + range("object-y", "Позиция Y, м", 0.5, 1.3, 0.01, controlScene ? 0.65 : 1) + range("object-z", "Позиция Z, м", -0.35, 0.35, 0.01, 0) + range("object-rotation", "Поворот Y, °", -180, 180, 1, 0) + range("light-power", "Яркость света", 0, 40, 0.1, 12) + range("light-size", "Размер света, м", 0.1, 1.2, 0.01, 0.6) + range("light-x", "Свет X, м", -0.35, 0.35, 0.01, 0) + range("light-z", "Свет Z, м", -0.35, 0.35, 0.01, 0) + range("wall-neutral", "Нейтральные стены", 0.05, 0.95, 0.01, 0.73) + range("wall-red", "Красная стена ×", 0.1, 1.5, 0.01, 1) + range("wall-green", "Зелёная стена ×", 0.1, 1.5, 0.01, 1))}
      ${group("Материал", select("material", "Тип", '<option value="diffuse">Диффузный</option><option value="glass">Стекло RGB</option><option value="nbk7">N-BK7</option><option value="nbk7-constant">N-BK7 без дисперсии</option>') + '<label class="check"><input id="dispersion" type="checkbox" checked disabled>Дисперсия N-BK7</label>' + range("ior", "Показатель IOR", 1, 2.5, 0.0001, nbk7Ior(587.6)) + range("absorption", "Поглощение ×", 0, 10, 0.05, 1) + range("albedo", "Диффузное альбедо", 0, 1, 0.01, 0.65) + '<p class="hint">При дисперсии IOR задаётся Sellmeier N-BK7. Поглощение меняет RGB и спектральные коэффициенты одинаково.</p>')}
      ${group("SPPM / Фотоны", '<label class="field"><span>Путей / итерацию</span><input id="photons" type="number" min="1" max="1048576" step="1024" value="16384" disabled></label>' + select("batch", "Путей / пакет", "<option>64</option><option>128</option><option>256</option><option>512</option><option selected>1024</option><option>2048</option><option>4096</option>") + range("radius", "Начальный радиус, м", 0.001, 0.2, 0.001, 0.03) + '<p class="hint">Малый радиус уточняет каустику, но требует больше фотонов. Пакет влияет на время порции и память.</p>')}
      ${group("Отображение", range("exposure", "Экспозиция, EV", -8, 8, 0.1, 0) + select("tone-mapper", "Tone mapping", '<option value="reinhard">Reinhard</option><option value="aces">ACES fit</option><option value="linear">Linear / clamp</option>') + '<label class="check"><input id="denoiser" type="checkbox" disabled>Denoiser à-trous</label>' + range("denoise-passes", "Проходы фильтра", 1, 5, 1, 3) + range("denoise-strength", "Сила фильтра", 0.1, 5, 0.1, 2) + '<label class="check"><input id="filter-glass" type="checkbox" disabled>Фильтровать стекло</label><p class="hint">Raw-накопление не меняется. Стекло по умолчанию не сглаживается: первая поверхность не описывает преломлённый фон.</p>', true)}
      ${group("Память и экспорт", select("memory-profile", "GPU-профиль", '<option value="192">Integrated / 192 MiB</option><option value="384">Desktop / 384 MiB</option>') + range("memory-budget", "Бюджет, MiB", 64, 384, 16, 192) + '<div class="export-buttons"><button id="export-png" disabled>PNG</button><button id="export-pfm" disabled>Raw PFM + JSON</button><button id="restart" disabled>Начать накопление заново</button></div><p id="export-status" class="hint">Экспорт доступен после полного прохода. PFM сохраняет линейный RGB, включая отрицательные компоненты.</p>')}
    </aside>
  </div>
  <footer class="statusbar"><strong id="status">Инициализация…</strong><p id="stats">Запрашиваем GPU-адаптер</p><span id="elapsed">00:00</span></footer>
</main>`;
}
